import type { Tour } from '@/content/tours/types'

export type { Tour, TourPoi } from '@/content/tours/types'

export const koelschKoelnTour: Tour = {
  slug: 'koelsch-koeln',
  area: 'Köln · Altstadt',
  title: 'Kölsch, Köbes und Kathedrale',
  subtitle:
    'Vom Dom bis ins Friesenviertel – 14 Stationen, 4 Brauhäuser, eine Stadt die niemals aufhört nachzuschenken',
  description:
    'Statt Bayrischem Bier geht es heute etwas kleiner zu – aber dafür trinkt ihr halt 1–2 mehr. Vorbei am Dom mit seiner 632-jährigen Baustellen-Geschichte, durch die Altstadt, am Rhein entlang – und dann von Brauhaus zu Brauhaus. Der Köbes schenkt nach, solange der Deckel nicht auf dem Glas liegt. Du bist gewarnt.',
  durationMin: 210,
  distanceKm: 6,
  triggerRadiusM: 100,
  start: { lat: 50.9413, lng: 6.9583 },
  pois: [
    {
      id: 'koelner-dom',
      order: 1,
      lat: 50.9413,
      lng: 6.9583,
      name: 'Kölner Dom',
      category: 'Geschichte / Architektur',
      durationSec: 90,
      tags: ['Geschichte', 'Architektur', 'Weltkulturerbe'],
      blurb: 'Über 600 Jahre Baustelle – nicht wegen Lieferproblemen, einfach aus Lustlosigkeit.',
      story:
        '1248 wurde der Grundstein gelegt. Dann passierte – nicht viel. 1473 ruhte die Baustelle einfach. Mit einem halbfertigen Turm und einem Kran, der über 400 Jahre stehen blieb – mitten in der Kölner Skyline. Er wurde so vertraut, dass er ins Kölner Stadtwappen aufgenommen wurde. Eine Stadt, die ihre Unfertigkeiten ins Wappen druckt. Das sagt alles. Erst 1880 war der Dom fertig – kurz das höchste Gebäude der Welt, für genau vier Jahre, bis das Washington Monument fertig war. Kölner Bauplanung: immer knapp am Weltrekord vorbei.',
      fact: 'Der Dom überstand den Zweiten Weltkrieg trotz 14 Bombentreffern. Die alliierten Piloten nutzten ihn als Navigationspunkt – das hat ihn möglicherweise vor der vollständigen Zerstörung bewahrt.',
      sinnlich:
        'Die Domplatte liegt offen und windig. Der dunkle Stein, die unzähligen Figuren, das Rauschen der Stadt dahinter – man braucht einen Moment, bis der Maßstab sitzt.',
      tipp: 'Von der Domplatte Richtung Rhein schauen – das Panorama mit Groß St. Martin im Hintergrund ist das Postkartenmotiv Kölns. Kostet nichts.',
      cta: 'Zwei Schritte weiter – ins älteste Brauhaus direkt am Dom. Und schnell lernen: Deckel auf das Glas legen, sonst trinkst du acht.',
    },
    {
      id: 'frueh-am-dom',
      order: 2,
      lat: 50.9398,
      lng: 6.9570,
      name: 'Früh am Dom',
      category: 'Brauhaus / Kölsch',
      tags: ['Kölsch', 'Brauhaus', 'Köbes', 'Brauhaus-Stop'],
      blurb: 'Erstes Kölsch der Tour – und die wichtigste Lektion der Stadt: Der Köbes bringt nach. Immer.',
      story:
        'Wer hier sitzt, lernt die wichtigste Regel Kölns: Der Köbes bringt einfach nach, ohne zu fragen. Solange, bis du den Bierdeckel auf dein Glas legst. Das ist kein Service – das ist ein Naturgesetz. Ein amerikanischer Tourist soll einmal gezählt haben: Er wollte zwei Kölsch trinken. Er bekam acht. Er hatte vergessen, den Deckel zu legen. Er fand Köln wunderbar.',
      fact: 'Kölsch hat eine EU-geschützte Herkunftsbezeichnung – darf nur im Umkreis von ca. 50 km um Köln gebraut werden. Wie Champagner, nur mit weniger Prestige und mehr Sturheit. Wer in Düsseldorf ein „Kölsch" bestellt, bekommt einen langen Blick.',
      sinnlich:
        'Das Kölsch kommt im schmalen 0,2-Liter-Stangen-Glas. Klein, klar, kühl. Der erste Schluck ist immer das beste Argument gegen alles andere.',
      tipp: 'Den Köbes nicht hetzen. Er hat das schon öfter gemacht als du – und keine Zeit für lange Bestellungen.',
      cta: 'Deckel weg, Kölsch rein, Prost. Weiter Richtung Alter Markt – dort steht ein Denkmal für eine Frau, die Nein sagte und es ihr Leben lang bereute.',
    },
    {
      id: 'alter-markt',
      order: 3,
      lat: 50.9382,
      lng: 6.9594,
      name: 'Alter Markt',
      category: 'Geschichte / Stadtkultur',
      durationSec: 75,
      tags: ['Geschichte', 'Denkmal', 'Liebe'],
      blurb: 'Ein Denkmal für einen Kriegshelden – und eine Bäckerstochter, die Nein sagte.',
      story:
        'Hier steht das Denkmal von Jan von Werth – Bauernsohn, später berühmter kaiserlicher Reitergeneral. Aber die Kölner erinnern sich vor allem an seine Jugend: Er warb um die Bäckerstochter Griet – sie lehnte ihn ab, er sei ihr nicht gut genug. Jahre später zog er als gefeierter General durch Köln. Griet stand im Publikum, inzwischen unverheiratet und verarmt. Jan soll ihr vom Pferd zugerufen haben: „Griet, wär\'t besser, du hättest mich genommen!" Sie antwortete: „Jan, wer dat gewoss hätt!" Diese Geschichte wird in Köln bis heute erzählt – eine ewige Mahnung: Niemals zu früh Nein sagen.',
      fact: 'Jan von Werth diente im Dreißigjährigen Krieg unter Kaiser Ferdinand II. und galt als einer der furchtbarsten Reiterführer seiner Zeit. Bauernjunge. Reichsgraf. Kölner Volkslegende. In dieser Reihenfolge.',
      sinnlich:
        'Der Alter Markt ist einer der belebtesten Plätze der Altstadt – Terrassen, Stimmengewirr, das Pflaster uneben und abgenutzt. Man spürt: Diese Stadt hat Geschichte unter den Füßen.',
      tipp: 'Das Rathaus daneben kurz anschauen – der gotische Rathausturm aus dem 15. Jahrhundert ist ein oft übersehenes Highlight.',
      cta: 'Wenige Schritte weiter – zur ältesten Kirche am Rheinufer. Im Mittelalter stand sie direkt neben dem Fischmarkt. Die Mönche haben sich beschwert.',
    },
    {
      id: 'gross-st-martin',
      order: 4,
      lat: 50.9372,
      lng: 6.9606,
      name: 'Groß St. Martin',
      category: 'Architektur / Geschichte',
      durationSec: 60,
      tags: ['Architektur', 'Romanik', 'Altstadt'],
      blurb: 'Zwölf romanische Kirchen in einer Stadt. Das ist kein Zufall – das ist eine Ansage.',
      story:
        'Groß St. Martin ist eine der zwölf romanischen Kirchen Kölns – ein Ensemble, das in dieser Dichte weltweit einmalig ist. Fertiggestellt im 12. Jahrhundert, im Zweiten Weltkrieg schwer beschädigt, bis 1985 vollständig restauriert. Im Mittelalter lag direkt daneben der städtische Fischmarkt. Historiker fanden lateinische Beschwerden der Mönche über den Gestank. Die Kirche steht noch. Der Fischmarkt auch – heute als Restaurant-Meile, mit deutlich weniger Gestank.',
      fact: 'Alle zwölf romanischen Kirchen Kölns wurden im Zweiten Weltkrieg zerstört oder schwer beschädigt – und alle zwölf wieder aufgebaut. Köln hat sich seine Kirchenlandschaft Stein für Stein zurückgebaut.',
      sinnlich:
        'Der charakteristische Vierungsturm überragt die Altstadtkulisse und ist vom Rhein her der erste Blickfang. Kein Zufall: Die Kirche wurde als Leuchtturm für Schiffer geplant.',
      tipp: 'Kurz hinein – die romanischen Bögen und die schlichte Monumentalität wirken nach dem Trubel draußen besonders.',
      cta: 'Weiter ans Rheinufer – zum schönsten Panorama der Stadt. Das größtenteils in den 1950ern nachgebaut wurde. Köln lügt sehr hübsch.',
    },
    {
      id: 'rheinufer-fischmarkt',
      order: 5,
      lat: 50.9360,
      lng: 6.9636,
      name: 'Rheinufer & Fischmarkt',
      category: 'Stadtbild / Panorama',
      durationSec: 60,
      tags: ['Panorama', 'Rhein', 'Altstadt'],
      blurb: 'Das Postkartenmotiv Kölns. Zu 90 Prozent Nachkriegsrekonstruktion.',
      story:
        'Das Rheinpanorama mit Groß St. Martin im Hintergrund ist DAS Postkartenmotiv Kölns. Was die meisten nicht wissen: Die hübsche Altstadt-Kulisse am Ufer ist zu einem großen Teil Nachkriegsrekonstruktion. Köln wurde zu über 90 Prozent zerstört – eine der am schwersten getroffenen deutschen Städte. Was heute mittelalterlich-malerisch aussieht, wurde größtenteils in den 1950ern wiederaufgebaut – inklusive der Giebelhäuser. Köln hat sich seine Schönheit einfach nachgebaut. Handwerklich sehr gute Arbeit. Respekt.',
      fact: 'Die Kölner Altstadt galt bis in die 1980er als heruntergekommenes Viertel. Erst gezielte Sanierungsprogramme schufen das heutige Bild – was nach alter Stadtkultur aussieht, ist ein sehr bewusstes Stadtentwicklungsprojekt.',
      sinnlich:
        'Der Rhein wirkt hier breiter als er ist. Rechtsrheinisch schlichte Wohnblöcke, linksrheinisch der Kirchturm. Der Gegensatz ist sehr Köln.',
      tipp: 'Kurz am Geländer stehen und Richtung Hohenzollernbrücke schauen – das ist das zweite große Panoramabild dieser Tour.',
      cta: 'Weiter Richtung Brücke – die unter 40 Tonnen Liebesschlössern ächzt. Und von der Stadtverwaltung aufgegeben wurde. Aus Liebe.',
    },
    {
      id: 'fischmarkt-uebergang',
      order: 6,
      lat: 50.9388,
      lng: 6.9647,
      name: 'Fischmarkt / Richtung Hohenzollernbrücke',
      category: 'Stadtleben',
      durationSec: 45,
      tags: ['Stadtleben', 'Rhein', 'Übergang'],
      blurb: 'Der meistfotografierte Spazierweg Kölns – auch wenn die meisten nicht wissen, was sie fotografieren.',
      story:
        'Die Uferpromenade zwischen Fischmarkt und Hohenzollernbrücke verbindet das mittelalterliche Altstadtbild mit dem industriellen Brückenbau des 19. Jahrhunderts. Hier wechselt Köln den Charakter – von gemütlich-historisch zu groß und offen. An warmen Abenden setzen sich Kölner mit Kölsch auf die Stufen, Gruppen spielen Musik, Touristen suchen den besten Fotowinkel. Das funktioniert seit Jahrzehnten, ohne dass jemand es organisiert.',
      fact: 'Der Rhein fließt hier mit bis zu 2 m/s – das entspricht einem zügigen Spaziergang. Wer ins Wasser fällt, wird schnell mitgenommen. Die Feuerwehr empfiehlt das Schwimmen ausdrücklich nicht. Mutige Kölner machen es trotzdem.',
      sinnlich:
        'Stromaufwärts: Dom, Brücke, Wasser, Himmel. Die Aufnahme, die auf jedem Köln-Kalender hängt. Und sie ist jedes Mal trotzdem gut.',
      tipp: 'Im Sommer die Ufertreppe runter – direkt ans Wasser, Füße baumeln lassen. Kölsch aus der Tasche ist erlaubt.',
      cta: 'Auf die Brücke – und aufpassen, dass du nicht über ein Liebesschloss stolperst.',
    },
    {
      id: 'hohenzollernbruecke',
      order: 7,
      lat: 50.9406,
      lng: 6.9694,
      name: 'Hohenzollernbrücke',
      category: 'Architektur / Kuriositäten',
      durationSec: 75,
      tags: ['Brücke', 'Liebesschlösser', 'Panorama'],
      blurb: 'Eine der meistbefahrenen Eisenbahnbrücken Europas. Plus 40 Tonnen Liebesschlösser. Die Stadt hat aufgegeben.',
      story:
        'Eine der meistbefahrenen Eisenbahnbrücken Europas – täglich über 1.200 Züge. Und gleichzeitig hängen über 500.000 Liebesschlösser an den Geländern. Geschätztes Gesamtgewicht: 40 Tonnen. Der Trend kam in den 2000ern aus Paris und erreichte in Köln eine besondere Dimension. Die Stadt hat mehrfach überlegt, die Schlösser zu entfernen. Petitionen, Debatten. Die Schlösser blieben. Irgendwann hat die Stadtverwaltung kapituliert – oder war selbst verliebt. Statiker sollen regelmäßig Alpträume haben.',
      fact: 'Die Brücke wurde 1911 eröffnet und im Zweiten Weltkrieg von der Wehrmacht selbst gesprengt, um den Vormarsch der Alliierten zu verlangsamen. 1948 wiederaufgebaut – seitdem Symbol für Kölner Resilienz. Und seit den 2000ern auch für Kölner Romantik.',
      sinnlich:
        'Der Blick zurück auf den Dom ist der beste Fotopunkt der Tour. Die Brücke vibriert leicht, wenn ein Zug passiert – das spürt man in den Füßen.',
      tipp: 'Eigenes Schloss mitbringen und hängen. Schlüssel in den Rhein. Kostet nur ein Schloss – und wird von hunderttausend anderen auch gemacht. Macht es nicht weniger bedeutsam.',
      cta: 'Zurück in die Altstadt – ins älteste Brauhaus der Tour. Gegründet bevor Kolumbus Amerika entdeckt hat. Kein Tippfehler.',
    },
    {
      id: 'brauhaus-sion',
      order: 8,
      lat: 50.9371,
      lng: 6.9579,
      name: 'Brauhaus Sion',
      category: 'Brauhaus / Geschichte',
      tags: ['Kölsch', 'Brauhaus', 'Geschichte', 'Brauhaus-Stop'],
      blurb: 'Gegründet 1318. Kein Tippfehler. Damals gab es noch kein Amerika und keine Kartoffel in Europa.',
      story:
        'Das Brauhaus Sion existiert seit 1318 – mehr als 700 Jahre in derselben Stadt, am selben Ort, mit demselben Auftrag: brauen, ausschenken, nachschenken. Zu diesem Zeitpunkt war der Dom noch im Bau (und würde es noch über 500 Jahre bleiben), die Pest hatte Europa noch nicht erreicht. Der Köbes hier schaut dich immer noch so an, als wärst du der Neue. Aus seiner Perspektive stimmt das: Im Vergleich zur Geschichte des Hauses ist jeder Gast neu.',
      fact: 'Das Kölsch, wie wir es heute kennen – hell, obergärig, 4,8% Alkohol im 0,2-Liter-Glas – ist eine relativ moderne Erfindung des 20. Jahrhunderts. Was Sion seit 1318 braute, war technisch ein anderes Bier. Der Kölner Geist war schon immer derselbe.',
      sinnlich:
        'Mitten in der Altstadt, rustikal und laut. Holztische, Bierdeckelstapel, das Klirren der Stangen-Gläser. Touristen und Kölner Stammgäste am selben Tisch.',
      tipp: 'Himmel un Ääd bestellen – Blutwurst mit Apfelmus und Kartoffelpüree. Das authentischste Gericht Kölns. Wer es noch nicht kennt: jetzt ist der Moment.',
      cta: '700 Jahre Tradition kann man nicht ignorieren – Prost. Weiter zum Gürzenich: ältestes Festhaus Europas, Kaiser und Könige tanzten hier. Heute kannst du einfach reingehen.',
    },
    {
      id: 'guerzenich',
      order: 9,
      lat: 50.9347,
      lng: 6.9578,
      name: 'Gürzenich',
      category: 'Geschichte / Architektur',
      durationSec: 60,
      tags: ['Geschichte', 'Mahnmal', 'Festhaus'],
      blurb: 'Ältestes noch genutztes Festhaus Europas. Daneben Trümmer – als Mahnmal. Köln feiert und erinnert gleichzeitig.',
      story:
        'Kölns historisches Festhaus, gebaut 1441–1447, gilt als eines der ältesten noch genutzten Tanzhäuser Europas. Hier empfingen Bürgermeister Kaiser und Könige – Friedrich III., Maximilian I., Karl V. – und tanzten mit ihnen. Im Zweiten Weltkrieg schwer beschädigt und wieder aufgebaut. Dabei ließ man die Ruine der danebenliegenden Alt-St.-Alban-Kirche bewusst als Mahnmal stehen. Heute sitzt man beim Karneval im Gürzenich und schaut durch das Fenster auf Trümmer. Köln kann das: feiern und erinnern, gleichzeitig, im selben Gebäude.',
      fact: '„Jemandem den Gürzenich geben" – also fürstlich bewirten – war im Mittelalter eine gebräuchliche Redewendung. 500 Jahre später veranstaltet die Kölner Karnevalsgesellschaft hier ihre Sitzungen. Die Kontinuität ist bemerkenswert.',
      sinnlich:
        'Die Ruine von Alt-St.-Alban direkt daneben: offene Mauern, kein Dach, Gras zwischen den Steinen. Darin eine Pietà als Gedenkfigur. Der Kontrast zum fröhlichen Festhaus nebenan ist sehr bewusst gesetzt.',
      tipp: 'Kurz in die Ruine von Alt-St.-Alban hineingehen. Ein stiller Moment inmitten der Tour.',
      cta: 'Weiter zum Heumarkt – Geheimtipp-Brauhaus für Kölner unter sich. Touristen werden trotzdem reingelassen, weil der Köbes genug für alle hat.',
    },
    {
      id: 'malzmuehle',
      order: 10,
      lat: 50.9347,
      lng: 6.9606,
      name: 'Brauerei zur Malzmühle',
      category: 'Brauhaus / Kölsch',
      tags: ['Kölsch', 'Brauhaus', 'Heumarkt', 'Brauhaus-Stop'],
      blurb: 'Das Kölsch, das Kölner trinken, wenn sie unter sich sind. Keine Speisekarte in sieben Sprachen.',
      story:
        'Die Malzmühle am Heumarkt ist der Geheimtipp, der eigentlich keiner mehr ist. Das hier gebraute Mühlen Kölsch hat eine treue Fangemeinde – die Küche gilt als eine der ehrlichsten der Stadt. Kein Schnickschnack. Der Heumarkt direkt davor ist einer der größten Plätze der Innenstadt – mit Jan-von-Werth-Brunnen, der die Geschichte vom Alter Markt nochmal in Szene setzt. Köln erzählt seine Geschichten gern zweimal.',
      fact: 'Der Heumarkt war jahrhundertelang der wichtigste Marktplatz Kölns – Heu, Stroh und Vieh. Heute Standort des Weihnachtsmarkts und Karneval-Hotspot. Der Boden darunter ist archäologisch reichhaltig und liefert regelmäßig Mittelalter-Funde.',
      sinnlich:
        'Das Malzmühlen-Kölsch kommt direkt und unkompliziert. Das Lokal ist eng, laut, warm. Im Sommer Außenplätze am Heumarkt – einer der angenehmsten Plätze Kölns an einem sonnigen Nachmittag.',
      tipp: 'Reibekuchen mit Apfelmus bestellen. Das ist die kölsche Antwort auf alle Fragen des Lebens.',
      cta: 'Halbzeit. Wer jetzt noch keinen Hunger hat, dem ist nicht zu helfen. Weiter Richtung Friesenviertel – durch zwei der lebendigsten Plätze der Stadt.',
    },
    {
      id: 'neumarkt',
      order: 11,
      lat: 50.9359,
      lng: 6.9486,
      name: 'Neumarkt',
      category: 'Stadtleben / Geschichte',
      durationSec: 60,
      tags: ['Stadtleben', 'U-Bahn', 'Geschichte'],
      blurb: 'Hier riss 2009 ein U-Bahn-Bau ein Archiv aus dem 10. Jahrhundert in die Tiefe. Die U-Bahn fährt. Das Archiv wird noch restauriert.',
      story:
        'Der Nord-Süd-Stadtbahn-Bau am Neumarkt war eines der größten Stadtbahnprojekte Deutschlands. Berühmt wurde er, weil 2009 das Historische Stadtarchiv Kölns in sich zusammensackte und in die Baugrube fiel. Das Archiv beherbergte Dokumente aus dem 10. Jahrhundert – Urkunden, Handschriften, Stadtprotokolle. Das kollektive Gedächtnis Kölns. Hunderte Freiwillige gruben tagelang Akten und Pergamente aus dem Schlamm. Das Archiv wird bis heute restauriert, Dokument für Dokument. Die U-Bahn fährt seit 2022. Köln hat Prioritäten – am Ende kriegt man beides hin.',
      fact: 'Das Historische Archiv der Stadt Köln ist eines der größten kommunalen Archive Europas, mit Beständen aus über 1.000 Jahren. Der Einsturz 2009 galt als eine der größten Kulturkatastrophen Deutschlands der Nachkriegszeit. Zwei Menschen kamen ums Leben.',
      sinnlich:
        'Einer der belebtesten Verkehrsknoten der Stadt – U-Bahn, Straßenbahn, Fußgänger, Einkaufsstraßen. Laut, voll, lebendig. Die Geschichte darunter spürt man nicht. Das ist das Tückische.',
      tipp: 'Kurz die Größe des Platzes realisieren. Dann weitergehen – der Friesenplatz wartet.',
      cta: 'Weiter zum Friesenplatz – und dann ins letzte Brauhaus der Tour. Das seit 1883 keinen Millimeter nachgegeben hat.',
    },
    {
      id: 'friesenplatz',
      order: 12,
      lat: 50.9406,
      lng: 6.9403,
      name: 'Friesenplatz',
      category: 'Stadtleben / Übergang',
      durationSec: 30,
      tags: ['Stadtleben', 'Friesenviertel'],
      blurb: 'Genau zwischen zwei Kölns – dem lauten Zentrum und dem ruhigeren Friesenviertel.',
      story:
        'Einer jener Kölner Plätze, die man kennt, ohne sie bewusst zu kennen. Kein großes Denkmal, keine berühmte Geschichte – aber eine wichtige Zäsur im Stadtbild. Wer hier ankommt, hat die Altstadt hinter sich. Vor ihm: das Friesenviertel – lebhaft, gastronomisch dicht, und am Ende die Brauerei Päffgen.',
      fact: 'Das Friesenviertel verdankt seinen Namen dem mittelalterlichen Friesentor, einem der alten Stadttore Kölns. Das Tor ist längst verschwunden, der Name blieb. So funktioniert Stadtgeschichte: Die Substanz geht, der Begriff bleibt.',
      sinnlich:
        'Die Luft verändert sich hier – weniger Tourismus, mehr Alltag. Kleine Restaurants, Bars, Anwohner. Das ist Köln, wie es von Kölnern bewohnt wird.',
      tipp: 'Einfach durchgehen – die wenigen Schritte zum nächsten Stopp sind die schönste Vorbereitung auf das letzte Brauhaus.',
      cta: 'Noch wenige Schritte – dann: Päffgen. Kein QR-Code, kein Social Media, kein Kompromiss. Nur Kölsch vom Fass.',
    },
    {
      id: 'paeffgen',
      order: 13,
      lat: 50.9409,
      lng: 6.9427,
      name: 'Brauerei Päffgen',
      category: 'Brauhaus / Kölsch',
      tags: ['Kölsch', 'Brauhaus', 'Friesenviertel', 'Brauhaus-Stop'],
      blurb: 'Gegründet 1883. Familiengeführt. Kölsch vom Holzfass. Keine Werbung. Kein QR-Code. Kein Kompromiss.',
      story:
        'Päffgen ist eine Institution. Gegründet 1883, bis heute familiengeführt, keine Kompromisse. Das Kölsch kommt direkt vom Holzfass. Keine Social-Media-Strategie, kein QR-Code, keine Speisekarte in Englisch mit Fotos. Es gibt: Kölsch. Bänke. Einen Köbes, der schon gesehen hat, wie Generationen kommen und gehen. Die Empfehlung „Reservierung empfohlen" ist wohltuend untertrieben – an Karnevalstagen stehen Menschen draußen Schlange wie für ein Konzert. Nur ohne Merchandise.',
      fact: 'Päffgen braut ausschließlich für den eigenen Ausschank – kein Päffgen Kölsch in Flaschen, kein Päffgen im Supermarkt. Was hier ausgeschenkt wird, wird nur hier ausgeschenkt. In Zeiten von Lizenzbrauerei ein echtes Statement.',
      sinnlich:
        'Das Kölsch kommt kühler als anderswo und hat eine leichte Spritzigkeit, die beim Fassausschank besonders deutlich ist. Holzbänke, altes Mobiliar, gedämpftes Licht. Seit 1883 hat sich nicht viel verändert. Das ist das Konzept.',
      tipp: 'Den Köbes nach dem aktuellen Fass fragen – manchmal gibt es besondere Chargen. Wer satt werden will: Kölner Küche, ehrlich und ohne Firlefanz.',
      cta: 'Das Finale verdient ein letztes Kölsch vom Fass – du hast es dir erlaufen. Prost. Noch ein paar Schritte ins Belgische Viertel – und der Tour-Abschluss.',
    },
    {
      id: 'belgisches-viertel',
      order: 14,
      lat: 50.9385,
      lng: 6.9427,
      name: 'Friesenviertel / Belgisches Viertel',
      category: 'Stadtleben / Abschluss',
      durationSec: 75,
      tags: ['Stadtleben', 'Belgisches Viertel', 'Abschluss'],
      blurb: '500 Meter vom letzten Brauhaus, eine andere Welt: Flat White, Concept Stores, Vintage-Läden. Und trotzdem: Köln.',
      story:
        'Das Belgische Viertel ist Kölns hippstes Quartier – Concept Stores, Spezialitätenkaffee, Vintage-Läden, Galerien. Keine 500 Meter vom Päffgen entfernt und könnte aus einer anderen Stadt sein. Hier bestellt man Flat White und diskutiert über Nachhaltigkeit. Drei Straßen weiter sitzt jemand beim fünften Kölsch und redet über den 1. FC Köln. Das ist Köln: zwei Welten, eine Stadt. Und am Ende treffen sich beide beim Karneval – auf der Straße, mit Kölsch in der Hand, ohne dass jemand fragt, was der andere beruflich macht.',
      fact: 'Nach dem Zweiten Weltkrieg als bescheidenes Wohnviertel wieder aufgebaut – günstige Mieten, einfache Struktur. Erst in den 2000ern wandelte es sich zum Szeneviertel. Die Gentrifizierung ist auch hier ein Thema – aber das Kölsch ist geblieben.',
      sinnlich:
        'Friesenstraße und Umgebung abends lebendig – Außengastronomie, Stimmengewirr, das Licht der Bars. Man sitzt und hört Köln.',
      tipp: 'Wer noch Energie hat: Maastrichter Straße und Aachener Straße flanieren. Wer keine mehr hat: nochmal Kölsch. Der Köbes wartet.',
      cta: 'Noch immer nüchtern? Dann einfach nochmal von vorne beginnen – der Dom läuft nicht weg, der Köbes auch nicht.',
    },
  ],
}
